name: sigmorphon19
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2018.03.07
  - certifi=2018.11.29
  - cffi=1.11.5
  - freetype=2.9.1
  - intel-openmp=2019.1
  - jpeg=9b
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.35
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - mkl=2019.1
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openssl=1.1.1a
  - pillow=5.3.0
  - pip=18.1
  - pycparser=2.19
  - python=3.7.1
  - readline=7.0
  - setuptools=40.6.3
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - tqdm=4.28.1
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pytorch=1.0.0
  - torchvision=0.2.1
  - pip:
    - torch==1.0.0